package com.futuretek.ww;

import gov.nasa.worldwind.Model;
import gov.nasa.worldwind.WorldWind;
import gov.nasa.worldwind.avlist.AVKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class WorldWindPanel extends javax.swing.JPanel {

	/**
	 * Creates new form WorldWindPanel
	 */
	public WorldWindPanel() {
		initComponents();
		// Create the default model as described in the current worldwind properties.
		Model m = (Model) WorldWind.createConfigurationComponent(AVKey.MODEL_CLASS_NAME);
		this.worldwindCanvas.setModel(m);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
	 * of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                worldwindCanvas = new gov.nasa.worldwind.awt.WorldWindowGLCanvas();

                setLayout(new java.awt.BorderLayout());
                add(worldwindCanvas, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private gov.nasa.worldwind.awt.WorldWindowGLCanvas worldwindCanvas;
        // End of variables declaration//GEN-END:variables
	public static void main(String args[]) {
		try {
			SwingUtilities.invokeAndWait(new Runnable() {
				public void run() {
					JFrame f = new JFrame("World Wind Demo");
					f.add(new WorldWindPanel());
					f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
					f.setSize(600, 600);
					f.setVisible(true);

				}
			});
		} catch (Exception ex) {
			Logger.getLogger(WorldWindPanel.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
}
